name: Aggregit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: michaeljolley/aggregit@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        type: ${{ secrets.type }}
        project_id: ${{ secrets.project_id }}
        private_key_id: ${{ secrets.private_key_id }}
        private_key: ${{ secrets.private_key }}
        client_email: ${{ secrets.client_email }}
        client_id: ${{ secrets.client_id }}
        auth_uri: ${{ secrets.auth_uri }}
        token_uri: ${{ secrets.token_uri }}
        auth_provider_x509_cert_url: ${{ secrets.auth_provider_x509_cert_url }}
        client_x509_cert_url: ${{ secrets.client_x509_cert_url }}
