name: Aggregit

on: [issue]

jobs:
  recordMetrics:
    runs-on: ubuntu-latest
    steps:
    - uses: michaeljolley/aggregit@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        project_id: ${{ secrets.project_id }}
        private_key: ${{ secrets.private_key }}
        client_email: ${{ secrets.client_email }}
        firebaseDbUrl: ${{ secrets.firebaseDbUrl }}
